spring:
  data:
    rest:
      base-path: /api/ver1
  application:
    name: laborape-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/laborape_db
    username: laborape
    password: laborape2025
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 4446
  error:
    include-stacktrace: always

logging:
  level:
    root: INFO # Default logging level for the whole application. Change it to DEBUG if you want to see very general logs.

    # Your base application package. Crucial to see logs of your own code.
    com.ulima.curso.softwareii.freelancedev: DEBUG

    # Spring Framework details
    org.springframework: INFO # General level for the Spring framework.
    org.springframework.boot: DEBUG # Boot details and Spring Boot configuration.
    org.springframework.web: DEBUG # Web request processing details (drivers, interceptors).

    # Spring Data JPA specific details
    org.springframework.data.jpa: DEBUG # To see how Spring Data JPA interacts with repositories.

    # Transaction and ORM details (JPA/Hibernate)
    org.springframework.orm.jpa: DEBUG # Level for JPA operations within Spring.
    org.springframework.transaction: TRACE # More detailed level for transaction management. This is very useful.

    # Hibernate configuration to view SQL statements and their parameters
    org.hibernate.SQL: DEBUG # Displays all SQL statements generated and executed by Hibernate.
    # To view the parameters that are bound to SQL queries:
    # Use this one for recent versions of Hibernate (5.2+ and Spring Boot 2.x+)
    org.hibernate.orm.jdbc.bind: TRACE