spring:
  data:
    rest:
      base-path: /api/ver1
  application:
    name: laborape-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/laborape_db
    username: laborape
    password: laborape2025
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    #user:
     #name: luis
     #password: gaaa
server:
  port: 4447